import { composePairCodeRepo, PairCodeStore } from "src/services/db/repositories/pairCode";
import { prisma } from "./prisma";

const table = prisma.pairCode;

export const pairCodeStoreSql: PairCodeStore = {
  create: async (userId) => {
    const row = await table.create({ data: { userId } });
    return row.code; // assume code PK generated by DB trigger/function
  },
  consume: async (code) => {
    const row = await table.findUnique({ where: { code } });
    if (!row) throw new Error("Pair code does not exist");

    await table.delete({ where: { code } });
    return { userId: row.userId, createdAt: row.createdAt };
  },
};

export const pairCodeRepoSql = composePairCodeRepo(pairCodeStoreSql);
